// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_tdd/test/services/todo_service_complex_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_tdd/models/priority.dart' as _i5;
import 'package:flutter_tdd/models/todo.dart' as _i4;
import 'package:flutter_tdd/models/todo_filter.dart' as _i6;
import 'package:flutter_tdd/repositories/todo_repository_interface.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TodoRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepositoryInterface extends _i1.Mock
    implements _i2.TodoRepositoryInterface {
  MockTodoRepositoryInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Todo>> getAllTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTodos, []),
            returnValue: _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i3.Future<List<_i4.Todo>>);

  @override
  _i3.Future<_i4.Todo?> getTodoById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTodoById, [id]),
            returnValue: _i3.Future<_i4.Todo?>.value(),
          )
          as _i3.Future<_i4.Todo?>);

  @override
  _i3.Future<void> addTodo(_i4.Todo? todo) =>
      (super.noSuchMethod(
            Invocation.method(#addTodo, [todo]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTodo(_i4.Todo? updatedTodo) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodo, [updatedTodo]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTodo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Todo>> getCompletedTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedTodos, []),
            returnValue: _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i3.Future<List<_i4.Todo>>);

  @override
  _i3.Future<List<_i4.Todo>> getPendingTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingTodos, []),
            returnValue: _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i3.Future<List<_i4.Todo>>);

  @override
  _i3.Future<List<_i4.Todo>> searchTodos(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTodos, [query]),
            returnValue: _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i3.Future<List<_i4.Todo>>);

  @override
  _i3.Future<List<_i4.Todo>> getTodosByCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getTodosByCategory, [category]),
            returnValue: _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i3.Future<List<_i4.Todo>>);

  @override
  _i3.Future<List<_i4.Todo>> getTodosByPriority(_i5.Priority? priority) =>
      (super.noSuchMethod(
            Invocation.method(#getTodosByPriority, [priority]),
            returnValue: _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i3.Future<List<_i4.Todo>>);

  @override
  _i3.Future<List<_i4.Todo>> getOverdueTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueTodos, []),
            returnValue: _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i3.Future<List<_i4.Todo>>);

  @override
  _i3.Future<List<_i4.Todo>> getDueSoonTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getDueSoonTodos, []),
            returnValue: _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i3.Future<List<_i4.Todo>>);

  @override
  _i3.Future<List<String>> getAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<_i4.Todo>> filterAndSortTodos(_i6.TodoFilter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#filterAndSortTodos, [filter]),
            returnValue: _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i3.Future<List<_i4.Todo>>);
}
